name: build
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 16 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Compile
        run: ./gradlew build
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: HuskSync
          path: build/libs/
